name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo pacman -Syyuu --noconfirm --needed clang cmake rust

    - name: Build
      run: cargo build --release

    - name: Compress
      run: |
        mkdir "$RUNNER_TEMP/$GITHUB_REF_NAME"
        cp -r ./target/release/moonlight-steam-shortcuts* README.md "$RUNNER_TEMP/$GITHUB_REF_NAME"
        cp LICENSE "$RUNNER_TEMP/$GITHUB_REF_NAME/LICENSE"
        tar caf "./moonlight-steam-shortcuts*-$GITHUB_REF_NAME-linux-amd64.tar.xz" -C "$RUNNER_TEMP" "$GITHUB_REF_NAME"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "./moonlight-steam-shortcuts*-*.tar.xz"
