name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo pacman -Syyuu --noconfirm --needed clang cmake rust

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Machete
      uses: bnjbvr/cargo-machete@main
